// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxlpfgekrwjflbbgujdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4bHBmZ2VrcndqZmxiYmd1amR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1MjQyMzksImV4cCI6MjA4NzEwMDIzOX0.iUthfkswmUzlKwD9UYAAiO5Dx95YdvgmgBcJDMjP9_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});